<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <UserSecretsId>cfc14362-f057-403e-bcfa-6a621d3037a2</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="RestAprilEducationRepository.AppHost\**" />
    <Compile Remove="RestAprilEducationRepository.ServiceDefaults\**" />
    <Content Remove="RestAprilEducationRepository.AppHost\**" />
    <Content Remove="RestAprilEducationRepository.ServiceDefaults\**" />
    <EmbeddedResource Remove="RestAprilEducationRepository.AppHost\**" />
    <EmbeddedResource Remove="RestAprilEducationRepository.ServiceDefaults\**" />
    <None Remove="RestAprilEducationRepository.AppHost\**" />
    <None Remove="RestAprilEducationRepository.ServiceDefaults\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Asp.Versioning.Http" Version="10.0.0" />
    <PackageReference Include="Asp.Versioning.Mvc.ApiExplorer" Version="10.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.7" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.7">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.23.0" />
    <PackageReference Include="Scalar.AspNetCore" Version="2.14.4" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Models\Repositories\" />
    <Folder Include="Models\Services\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\RestAprilEducationRepository.Application\RestAprilEducationRepository.Application.csproj" />
    <ProjectReference Include="..\RestAprilEducationRepository.Persistence\RestAprilEducationRepository.Persistence.csproj" />
    <ProjectReference Include="RestAprilEducationRepository.ServiceDefaults\RestAprilEducationRepository.ServiceDefaults.csproj" />
   
  </ItemGroup>

</Project>
